### ISSUE TITLE
There is no callback to recognised if user clicks on No thanks button?

### ISSUE THREAD

**Issue by aman007jham** [pollfish/android-sdk-pollfish#1]
If user clicks on No thanks button and if user try to click once again that survey button nothing is happening. But if user comes again in that page then its coming fine, Can you guys tell me how to recognised no thanks button click?

**Comment by vourkosa** [comment]
There is no official way to track "No thanks" button by user. 

A workaround would be to check PollFish.isPollfishPresent(); after onPollfishClosed(){} is fired. If survey is still present you can show it. Let me know if that helps

**Comment by aman007jham** [comment]
Thanks @vourkosa for sharing the info its really helpful, now my issue also fixed.
