### ISSUE TITLE
Pollfish leaks websocket connection

### ISSUE THREAD

**Issue by ivorsmorenburg** [pollfish/android-sdk-pollfish#11]
OkHttpClient: A connection to https://wss.pollfish.com/ was leaked. Did you forget to close a response body?

**Comment by Espremea** [comment]
Issue is still present. I noticed that by looking at the logs of my application. I doubt I can do much on my end...

**Comment by jhon558** [comment]
Bn yomen engargo

**Comment by ivorsliide** [comment]
Are you alright @jhon558? or you have a tick when writting? Alomejor quieres decir "Bien yo me encargo"? Will be nice to use english....
