### ISSUE TITLE
Incompatible with AWSMobileClient

### ISSUE THREAD

**Issue by esathamzaj** [pollfish/android-sdk-pollfish#14]
I use AWSMobileClient and when I make a release build I get this error message. 

>     Process: xxxxxxxxxxxx PID: 14924
>     java.lang.RuntimeException: Unable to create application xxxxxxxxxxxx.XXXApplication: java.lang.RuntimeException: Failed to read awsconfiguration.json please check that it is correctly formed.
>         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
>         at android.app.ActivityThread.access$1300(ActivityThread.java:237)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
>         at android.os.Handler.dispatchMessage(Handler.java:106)
>         at android.os.Looper.loop(Looper.java:223)
>         at android.app.ActivityThread.main(ActivityThread.java:7656)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
>      Caused by: java.lang.RuntimeException: Failed to read awsconfiguration.json please check that it is correctly formed.
>         at com.amazonaws.mobile.config.AWSConfiguration.<init>(AWSConfiguration.java:13)
>         at xxxxxxxxxxxx.onCreate(xxxxxxxxxxxx.kt:31)
>         at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
>         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
>         at android.app.ActivityThread.access$1300(ActivityThread.java:237) 
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913) 
>         at android.os.Handler.dispatchMessage(Handler.java:106) 
>         at android.os.Looper.loop(Looper.java:223) 
>         at android.app.ActivityThread.main(ActivityThread.java:7656) 
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
>      Caused by: org.json.JSONException: End of input at character 0 of
>         at org.json.JSONTokener.syntaxError(JSONTokener.java:460)
>         at org.json.JSONTokener.nextValue(JSONTokener.java:101)
>         at org.json.JSONObject.<init>(JSONObject.java:165)
>         at org.json.JSONObject.<init>(JSONObject.java:182)
>         at com.amazonaws.mobile.config.AWSConfiguration.<init>(AWSConfiguration.java:12)
>         xxxxxxxxxxxx.onCreate(xxxxxxxxxxxx.kt:31) 
>         at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192) 
>         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712) 
>         at android.app.ActivityThread.access$1300(ActivityThread.java:237) 
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913) 
>         at android.os.Handler.dispatchMessage(Handler.java:106) 
>         at android.os.Looper.loop(Looper.java:223) 
>         at android.app.ActivityThread.main(ActivityThread.java:7656) 
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
> 2021-12-09 15:27:06.759 14924-14960/? V/FA: Connecting to remote service
> 

Maybe there is a conflict between dependencies but I don't know why it works on debug builds. I also added the proguard rules as specified.

FYI: Disabling proguard fixes this issue.

**Comment by kaspanvo** [comment]
@esathamzaj can you please share the proguard rules and maybe any other flags used in the gradle build file around the release version?

**Comment by esathamzaj** [comment]
@kaspanvo  we have added these two lines 

-dontwarn com.pollfish.**
-keep class com.pollfish.** { *; }

https://developer.android.com/studio/build/shrink-code#keep-resources
We used this method to keep that specific file and it worked so somehow these two proguard rules of pollfish are causing that behaviour for that file to not be kept.

**Comment by esathamzaj** [comment]
Turns out this was a Pollfish SDK problem, so I'm closing this issue.
