### ISSUE TITLE
Pollfish causes issue with code-shrinker r8 in android

### ISSUE THREAD

**Issue by vinoch1992** [pollfish/android-sdk-pollfish#15]
I am using pollfish SDK to show survey in the app. When I enable code-shrinker r8, then the pollfish does not open the survey and there is no any event callbacks happening. If I remove the code-shrinker then pollfish works fine.

I tried to ignore the pollfish classes in proguard but still no luck with that.

`-keep class com.pollfish.**`

Please let me know how to solve this problem.

**Comment by fotism23** [comment]
Hello @vinoch1992 

Please replace the above with the following rules

```
-dontwarn com.pollfish.**
-keep class com.pollfish.** { *; }
```

Did this resolve your issue?

**Comment by vinoch1992** [comment]
@fotism23 thanks. This works like charm.

**Comment by fotism23** [comment]
Anytime @vinoch1992
