### ISSUE TITLE
Please always update the build.gradle file with the latest Pollfish dependency version

### ISSUE THREAD

**Issue by RahulSDeshpande** [pollfish/android-sdk-pollfish#3]
Current sample project is having the Pollfish dependency verion as **4.3.1** as below:
```
compile 'com.pollfish:pollfish:4.3.1:googleplayRelease@aar'
```

Due to this, many UserProperties class' subclasses are missing.

**Please update this to whatever the latest lib version** is, as it might create a confusion among the Pollfish devs about the latest stable Pollfish lib.

:)

Cheers Pollfish !!

**Comment by kaspanvo** [comment]
Thanks for the note @RahulSDeshpande!

**Comment by RahulSDeshpande** [comment]
Very welcome !!
And thanks a lot for accepting my Pull Request & merging it in the main branch !!

Cheers !!
