### ISSUE TITLE
 PollFish.show() not start a survey from different context.

### ISSUE THREAD

**Issue by ominfowave** [pollfish/android-sdk-pollfish#6]
I have to show PollFish ads from 7-8 different place, so I have created a common class to load the PollFish survey but issue is ,Suppose I have requested PollFish SDK to load Ads` (loadPollFish()) ` from `ActivityHome` and try to display`(show())` from `ActivityNew` it will not open the survey.

I have tested if I will update the activity context it's working, How to resolve this issue.
Want to load Survey Globally, and use it in any activity.

```
public class RewardPollFishHelper implements PollfishSurveyCompletedListener, PollfishClosedListener, PollfishOpenedListener, PollfishSurveyReceivedListener, PollfishUserNotEligibleListener {

    private static RewardPollFishHelper rewardPollFishHelper;
    private RewardBaseHelper.RewardAccessStatus rewardAccessStatus;
    private Activity activity;

    private RewardPollFishHelper(Activity activity) {
        this.activity = activity;
        loadPollFish(activity);
    }

    public static RewardPollFishHelper getInstance(Activity activity) {
        if (rewardPollFishHelper == null)
		{ 
			rewardPollFishHelper = new RewardPollFishHelper(activity);
			rewardPollFishHelper.loadPollFish(activity);
        }   
		else if(!isPollFishLoaded())
		{
			rewardPollFishHelper.loadPollFish(activity);
		}
			
        rewardPollFishHelper.activity = activity;
        return rewardPollFishHelper;
    }

    public static boolean isPollFishLoaded() {
        return PollFish.isPollfishPresent() && PollFish.isPollfishPresent();
    }

    private void loadPollFish(Activity activity) {
        PollFish.ParamsBuilder paramsBuilder = new PollFish.ParamsBuilder(activity.getString(R.string.poll_fish_key))
                .pollfishSurveyCompletedListener(this)
                .pollfishClosedListener(this)
                .pollfishOpenedListener(this)
                .pollfishSurveyReceivedListener(this)
                .pollfishUserNotEligibleListener(this)
                .releaseMode(false)
                .customMode(true)
                .build();

        // set release mode
        PollFish.initWith(activity, paramsBuilder);
        PollFish.hide();
    }


    public boolean show(RewardBaseHelper.RewardAccessStatus rewardAccessStatus) {


        this.rewardAccessStatus = rewardAccessStatus;

        LogUtils.debug("PollFishShow Favorite show " + activity);
        if (isPollFishLoaded()) {
            PollFish.show();
            return true;
        }
        return false;
    }


    @Override
    public void onPollfishSurveyCompleted(boolean b, int i) {
        LogUtils.debug("PollFish Favorite onPollfishSurveyCompleted " + rewardAccessStatus);
        if (rewardAccessStatus != null) {
            rewardAccessStatus.rewarded(RewardBaseHelper.ACCESS_FOR_NUMBER_OF_HOUR_24);
        }

    }

    @Override
    public void onPollfishClosed() {
        LogUtils.debug("PollFish Favorite onPollfishClosed " + rewardAccessStatus);
        if (rewardAccessStatus != null) {
            rewardAccessStatus.closed();
        }

    }

    @Override
    public void onPollfishOpened() {
        LogUtils.debug("PollFish Favorite onPollfishOpened " + rewardAccessStatus);

    }

    @Override
    public void onPollfishSurveyReceived(boolean b, int i) {
        LogUtils.debug("PollFish Favorite onPollFishSurveyReceived" + b + " == " + i);
     
    }

    @Override
    public void onUserNotEligible() {
        LogUtils.debug("PollFish Favorite onUserNotEligible");
    }
}

```

**Comment by kaspanvo** [comment]
the sdk get's the activity context and reverse traverse the tree to find the top view in order to add Pollfish overlay. When you change the activity you need to init again the sdk in order to get the right context.

**Comment by ominfowave** [comment]
`PollFish.initWith(activity, paramsBuilder);` always load a new survey even load survey is there and not expired, how can I change the context?

is it a good idea to load it from each activity,  if we have multiple activities.

What happens in the below case

1) Suppose I loaded survey from `ActivityA`, now I have started `ActivityB` and again loading survey from ActivityB, once I come back to `ActiivtyA` by closing ActivityB and try to display survey. Will it work or not?

2) What is cash when i want to display Survey from Fragment

**Comment by kaspanvo** [comment]
Pollfish initWith always load a new survey (request a new survey from server). During initialization the context of the activity is used to reverse traverse the tree and find the top rendering view in order to add Pollfish overlay. Every time you change between activities (even if activity comes to foreground/background) you should call Pollfish initWith in every activity. It is good practise to init within the onResume method to achieve the desired behaviour.

In fragments you should have reference to the context of the activity in order for Pollfish work properly.
