### ISSUE TITLE
onPollfishSurveyNotAvailable

### ISSUE THREAD

**Issue by AmitPalIntigate** [pollfish/android-sdk-pollfish#8]
Hello,

I have integrated in my project and I have got survey once per device after once I am getting callback all ways in this method onPollfishSurveyNotAvailable.

can you guide me how can i fix this issue.

Thanks,
Amit Pal

**Comment by kaspanvo** [comment]
Hello Amit, can you share your logs? Are you testing in test mode?

**Comment by AmitPalIntigate** [comment]
I have set release mode true

**Comment by AmitPalIntigate** [comment]
yes i am in testing mode

**Comment by kaspanvo** [comment]
you need to set releaseMode(false) to be able to receive a test survey every time. This is the right way to test Pollfish.

**Comment by AmitPalIntigate** [comment]
ok and for release mode I will get every time of survey when my app live on play store

**Comment by kaspanvo** [comment]
you will get a survey when a survey is available for that user. You need through to publish your app first on Google Play in release mode true and request your account to get verified prior being able to receive surveys from Pollfish clients

**Comment by AmitPalIntigate** [comment]
ok fine so can i test with uploading beta version on play store.
