### ISSUE TITLE
Not getting any call back sometime in my samsung device

### ISSUE THREAD

**Issue by AmitPalIntigate** [pollfish/android-sdk-pollfish#9]
Hello,

Some time I am not getting any call back from survey 

initializing by this

   PollFish.ParamsBuilder paramsBuilder = new PollFish.ParamsBuilder("a803d8fe-accf-4f80-bd24-e4ebee6e7d3d")
                .indicatorPadding(5)
                .customMode(true)
                .releaseMode(false)
                .build();
        PollFish.initWith(mActivity, paramsBuilder);

my call back listener are

 @Override
    public void onPollfishClosed() {
        CommonUtils.showLog("Pollfish", "onPollfishSurveyClose()");
        if (withdrawAmountBinder!=null)
            withdrawAmountBinder.onPollfishClosed();
    }

    @Override
    public void onPollfishSurveyCompleted(boolean b, int i) {
        CommonUtils.showLog("Pollfish", "onPollfishSurveyCompleted()");
        if (withdrawAmountBinder!=null)
            withdrawAmountBinder.onPollfishSurveyCompleted(b,  i);
    }

    @Override
    public void onPollfishSurveyNotAvailable() {
        CommonUtils.showLog("Pollfish", "onPollfishSurveyNotAvailable()");
        if (withdrawAmountBinder!=null)
            withdrawAmountBinder.onPollfishSurveyNotAvailable();
    }

    @Override
    public void onPollfishSurveyReceived(boolean b, int i) {
        CommonUtils.showLog("Pollfish", "onPollfishSurveyReceived()");
        if (withdrawAmountBinder!=null)
            withdrawAmountBinder.onPollfishSurveyReceived(b,i);
    }

    @Override
    public void onUserNotEligible() {
        CommonUtils.showLog("Pollfish", "onUserNotEligible()");
        if (withdrawAmountBinder!=null)
            withdrawAmountBinder.onUserNotEligible();
    }

but some time i am not getting any call back from survey

**Comment by kaspanvo** [comment]
What are the logs that you see?

**Comment by AmitPalIntigate** [comment]
I did not get any logs

**Comment by AmitPalIntigate** [comment]
I am getting this in my samsung device somtimes happning this issue otherwise it's working perfect

**Comment by kaspanvo** [comment]
when you have any logs please do share in order to be able to help.
